[tool.poetry]
name = "brasa"
version = "0.0.1"
description = "Python library to extract finance market data from brazillian financial institutions: B3, ANBIMA, Tesouro Direto, CVM."
authors = ["wilsonfreitas <wilson.freitas@gmail.com>"]
license = "MIT"
readme = "README.md"
include = [{ path = "brasa" }, { path = "templates" }]

[tool.poetry.dependencies]
python = "^3.10"
lxml = "^4.9.2"
bizdays = "^1.0.15"
pandas = "^2.0.0"
numpy = "^2.0.0"
xlrd = "^2.0.1"
regexparser = "^0.1.0"
pyyaml = "^6.0"
pyarrow = "^19.0.0"
progressbar2 = "^4.3.2"
html5lib = "^1.1"
beautifulsoup4 = "^4.12.2"
python-bcb = "0.3.2"
duckdb = "^1.2.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.15.3"
matplotlib = "^3.7.1"
mypy = "^1.9.0"
types-pyyaml = "^6.0.12.20241230"
types-pytz = "^2024.2.0.20241221"
types-requests = "^2.32.0.20241016"
types-lxml = "^2024.12.13"


[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"


[tool.poetry.group.tests.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]

[[tool.mypy.overrides]]
module = ["pandas.*", "regexparser.*", "bcb.*", "pyarrow.*", "bizdays.*"]
ignore_missing_imports = true
