"""Tests for TemplateConversionAgent."""

from __future__ import annotations

from pathlib import Path

import yaml

from brasa.agents import TemplateConversionAgent


def _write_template(path: Path, payload: dict) -> None:
    path.write_text(
        yaml.safe_dump(payload, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def test_propose_and_apply_conversion(tmp_path: Path) -> None:
    template_path = tmp_path / "demo-template.yaml"
    mapping_dir = tmp_path / "mappings"

    template = {
        "id": "demo-template",
        "description": "Demo template",
        "etl": {
            "function": "brasa.etl.create_b3_companies_cash_dividends",
            "cash_dividends_dataset": "b3-cash-dividends",
            "company_info_cash_dividends_dataset": "b3-company-info-cash_dividends",
        },
    }
    _write_template(template_path, template)

    agent = TemplateConversionAgent(mapping_dir=mapping_dir)
    proposal = agent.propose(template_path)

    assert proposal.skipped is False
    assert proposal.options
    assert proposal.options[0].valid is True

    agent.apply(proposal, option_index=0)

    updated = yaml.safe_load(template_path.read_text(encoding="utf-8"))
    assert "pipeline" in updated["etl"]
    assert updated["writer"]["partitioning"] == ["refdate"]

    mapping_path = mapping_dir / "demo-template.yaml"
    mapping_content = mapping_path.read_text(encoding="utf-8")
    assert mapping_content.startswith("# Mapping generated by template skills agent")


def test_skip_pipeline_template(tmp_path: Path) -> None:
    template_path = tmp_path / "pipeline-template.yaml"
    mapping_dir = tmp_path / "mappings"

    template = {
        "id": "pipeline-template",
        "etl": {"pipeline": [{"step": "load", "template": "demo"}]},
    }
    _write_template(template_path, template)

    agent = TemplateConversionAgent(mapping_dir=mapping_dir)
    proposal = agent.propose(template_path)

    assert proposal.skipped is True
    assert proposal.options == []
